### ISSUE TITLE
Parameterize Terraform for the Application Tier

### ISSUE THREAD

**Issue by robfallows** [Azure/sap-hana#510]
# Problem statement

The hardwired Terraform for (A)SCS needs to be parameter driven.
 
## Enhancement

Update configuration with sources for data
- User input data
- Static IP generation based on subnet ranges and counts
- Ensuring unique naming structures for all resources
- HA

**Notes

**Dependencies**

The following information will require defining (WIP list):

- [x] Subnet range(s)
- [x] SID for application tier (separate definition from database SID for use case where only application layer is deployed)
- [x] SCS Instance number
- [x] ERS Instance number
- [x] ~PAS Instance number~
- [x] VM Image details - #549
- [x] Private IP Addresses based on Subnets - #549
- [x] VM SSH Authentication details (username, authentication type, password details, ssh key details) - #549

**Checklist
